# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: matjek
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
permalink: /:year/:month/:day/:title
repository: cyberglad
paginate: 5

# MatJek specific configurations
github_profile: "https://cyberglad.github.io"
user: "Yuri Gladkov"
user_email: "cyberglad@gmail.com"
contact_url: "https://goo.gl/tVljbV"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"
disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
# Site settings
title:
  en: Yuri Gladkov - Java/.NET Developer
  fr: Iouri Gladkov - Developpeur Java/.NET
  de: Yuri Gladkov - Java/.NET Entwickler
  lu: Iouri Gladkov - Java/.NET Entwéckler
  es: Yuri Gladkov - Desarollo Java/.NET
  it: Yuri Gladkov - Sviluppo Java/.NET
  ru: Yuri Gladkov - разработчик Java/.NET
email: cyberglad@gmail.com
description:
  en: Yuri Gladkov - Java/.NET Developer
  fr: Iouri Gladkov - Developpeur Java/.NET
  de: Yuri Gladkov - Java/.NET Entwickler
  lu: Iouri Gladkov - Java/.NET Entwéckler
  es: Yuri Gladkov - Desarollo Java/.NET
  it: Yuri Gladkov - Sviluppo Java/.NET
  ru: Yuri Gladkov - разработчик Java/.NET
index:
  en:
  fr: accueil.html
  de: willkommen.html
  lu: wellkomm.html
  es: bienvenidos.html
  it: benvenuti.html
  ru: dobro.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cyberglad
github_username:  cyberglad

# Build settings
markdown: kramdown

t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/contact"
    experience:
      name: "Work Experience"
      url: "/projects"
    cv:
      name: "Resume"
      url: "/resume_en"
    contact:
      name: "Contact"
      url: "/contact"
  fr:
    home:
      name: "Accueil"
      url: "/accueil/"
    about:
      name: "À propos"
      url: "/contact_fr"
    experience:
      name: "Parcours professionel"
      url: "/projets"
    cv:
      name: "CV"
      url: "/resume"
    contact:
      name: "Contacter"
      url: "/contact_fr"
  de:
    home:
      name: "Willkommen"
      url: "/"
    about:
      name: "Über mich"
      url: "/contact"
    experience:
      name: "Berufserfahrung"
      url: "/projekte"
    cv:
      name: "CV"
      url: "/resume_en"
    contact:
      name: "Kontakt"
      url: "/contact"
  it:
    home:
      name: "Benvenuti"
      url: "/benvenuti/"
    about:
      name: "Sopra di me"
      url: "/contact"
    experience:
      name: "Esperienza"
      url: "/projects"
    cv:
      name: "CV"
      url: "/resume"
    contact:
      name: "Contattare"
      url: "/contact"
  es:
    home:
      name: "Bienvenidos"
      url: "/bienvenidos/"
    about:
      name: "Sobre mi"
      url: "/contact"
    experience:
      name: "Esperienza"
      url: "/projects"
    cv:
      name: "CV"
      url: "/resume"
    contact:
      name: "Contactar"
      url: "/contact"
  lu:
    home:
      name: "Wëllkomm"
      url: "/wellkomm/"
    about:
      name: "Iwwer mech"
      url: "/contact"
    experience:
      name: "Berufserfahrung"
      url: "/projects"
    cv:
      name: "CV"
      url: "/resume"
    contact:
      name: "Kontaktéiren"
      url: "/contact"

